TimeEncoder:
  enabled: True
  input_dim: 512
  output_dim: 512
  activation_func: ELU
  architecture: [512, 512]
  final_activation: ELU
ThetaEncoder:
  output_dim: 128
  architecture: [256]
  activation_func: ReLU
  final_activation: ReLU
SimulatorEncoder:
  output_dim: 128
  architecture: [256]
  activation_func: ReLU
  final_activation: ReLU
LatentMLP:
  architecture: [256, 156, 128]
  activation_func: ReLU
  final_activation: Softplus
