TimeEncoder:
  enabled: True
  input_dim: 64
  n_layers: 2
  hidden_dim: 64
ThetaEncoder:
  enabled: True
  output_dim: 128
  n_layers: 1
  hidden_dim: 64
SimulatorEncoder:
  enabled: True
  n_layers: 1 
  hidden_dim: 64
  output_dim: 128
LatentMLP:
  net_type: "res_net"
  n_target: ${dataset.n_target}
  n_layers: 5 
  hidden_dim: 64
  dropout_prob: 0.0
  use_batch_norm: false   

final_activation: Softplus
standardize: false