betas: [10, 100, 1000]
n_samples: 1000
data_entity: "gaussian_mixture"
observed_data_file: data/gbi_data/specified_known/${data_entity}_10 .pt
simulator: ${data_entity}  # same argument as in generate dataset, has to fit to the observed data file.    