betas: [10, 25, 75]
n_samples: 1000
data_entity: "gaussian_mixture"
observed_data_file: data/gbi_data/misspecified_unknown/${data_entity}_50.pt
simulator: ${data_entity}  # same argument as in generate dataset, has to fit to the observed data file.    
      