kernel: "NUTS"  # also HMC possible
beta: 1
prior: "SymmetricUniform" 
warmup_steps: 200

# Collection of prior distributions

SymmetricUniform:
  amplitude: 1
  n_dims: 2  # depended on the parameter dimension of a simulator. 
