results_dir: "results"
check_val_every_n_epochs: 5
num_worker: 8

train_file: "data/moon_1000.pt"
val_file: "data/moon_100.pt"
n_target: 10

max_epochs: 400
batch_size: 128
precision: 32 # 64: extended, 32: standard, 16: half

model:
    latent_dim: 256
    theta_encoder: [256]
    simulator_encoder: [256]
    latent_mlp: [256, 256, 128]
    activation_func: ReLU

optimizer:
    name: Adam
    lr: 0.0002
    weight_decay: 0

