# main.yaml
defaults:
  - _self_
  - hydra: hydra
  - dataset: dataset
  - model: diffusion_model 
  - diffusion: diffusion
  - optimizer: optimizer

data_entity: two_moons
check_val_every_n_epochs: 5
num_worker: 8  

max_epochs: 100 
batch_size: 256
precision: 32  # 64: extended, 32: standard, 16: half
