results_dir: "results"
check_val_every_n_epochs: 5
num_worker: 12


max_epochs: 100
batch_size: 256
precision: 32 # 64: extended, 32: standard, 16: half


dataset:
    train_file: "data/moon_1000.pt"
    val_file: "data/moon_100.pt"
    n_target: 20
    noise_std: 0.1  # how strong to noise the augmentations in x_target 


model:
    latent_dim: 256
    theta_encoder: [256]
    simulator_encoder: [256]
    latent_mlp: [256, 256, 128]
    activation_func: ReLU
    final_activation: null  # Sigmoid only needed for cosine similarity -> otherwise null


optimizer:
    name: Adam
    lr: 0.0001
    weight_decay: 0

